### ISSUE TITLE
[IDE][Android] Android Studio is missing

### ISSUE THREAD

**Issue by gperdomor** [ubuntu/ubuntu-make#302]
Hi, what happen with android studio?

**Comment by LyzardKing** [comment]
Hi,
Android studio and the sdk changed the download pages significantly.
They've been fixed in master, and will be working again in the next release.

**Comment by akshar-patel** [comment]
ERROR: A default framework for category Android was requested where there is none

Please release update as soon as possible.

**Comment by gperdomor** [comment]
@LyzardKing any ETA for the next release? I need it :(

**Comment by LyzardKing** [comment]
If you need you can clone the repository and install from that.
It's less than ideal, but if it can help you for the time being.

```
git clone https://github.com/ubuntu/ubuntu-make
cd ubuntu-make
bin/umake android
```

**Comment by marcinant** [comment]
IMHO it's still not fixed.

Just cloned umake as described above and I got this message:
> ERROR: We were expecting to find a license on the download page, we didn't.

**Comment by akshar-patel** [comment]
@marcinant same here. This needs to be fixed.

**Comment by rakshithravi1997** [comment]
I can confirm that Android Studio and Android SDK are working on the latest commit as of writing. Arduino IDE, however, isn't

**Comment by LyzardKing** [comment]
There's already a pull request for arduino.
The issue with all these is that openjdk-7 has been removed from the 
main repositories.
So we had to add openjdk-8 to every one.
 From my tests, as soon as arduino is fixed everything should be 
installable on 16.04

**Comment by rakshithravi1997** [comment]
Good to hear! Any estimate on when it will be added to the main servers? For people who don't follow this thread should also get the update for this is a very crucial fix

**Comment by istsehrgut** [comment]
@LyzardKing where are you seeing arduino?

`umake ide arduino
usage: umake ide [-h]
                 {rubymine,phpstorm,idea-ultimate,pycharm,visual-studio-code,datagrip,eclipse-cpp,eclipse-php,pycharm-professional,pycharm-educational,webstorm,clion,eclipse-jee,idea,eclipse,lighttable}
                 ...
umake ide: error: argument framework: invalid choice: 'arduino' (choose from 'rubymine', 'phpstorm', 'idea-ultimate', 'pycharm', 'visual-studio-code', 'datagrip', 'eclipse-cpp', 'eclipse-php', 'pycharm-professional', 'pycharm-educational', 'webstorm', 'clion', 'eclipse-jee', 'idea', 'eclipse', 'lighttable')`

**Comment by LyzardKing** [comment]
The arduino ide should work in Ubuntu 15.10 and previous versions.
In 16.04 it needs the fix in the pull request (dependency on openjdk-8)

**Comment by LyzardKing** [comment]
Closing since all this should work in the new release (16.05)

**Comment by ctrom** [comment]
Is there any chance of having this backported to xenial (16.04)? I see that the fix has been released for yakkety (16.10).

**Comment by LyzardKing** [comment]
Hi,
You need to add the ppa to get the latest version.
It's updated frequently as it's easier to upload a version to a ppa.

$ sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
$ sudo apt update
$ sudo apt install ubuntu-make

This way it'll install the latest release version (at the moment 16.05)
