### ISSUE TITLE
ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by andresrivas1506** [ubuntu/ubuntu-make#328]
```bash
$ uname -a
Linux andres-ts 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ umake --version
16.05

$ umake -v ide eclipse
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: ruby isn't installed
INFO: openjdk-7-jre isn't installed
INFO: openjdk-7-jre isn't installed
Choose installation path: /home/andres/.local/share/umake/ide/eclipse
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
INFO: https://www.eclipse.org/downloads/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable
```

**Comment by LordKrabo** [comment]
Encountering the same issue with Linux Mint 17.3 using the Ubuntu Make repositories.

**Comment by LyzardKing** [comment]
It's been fixed in master (#326).
The repository has not been updated yet.

**Comment by didrocks** [comment]
@LyzardKing I'm getting some issues as well from master:
```
$ bin/umake ide eclipse
Choose installation path: /home/didrocks/.local/share/umake/ide/eclipse
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/home/didrocks/work/ubuntu-make/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/home/didrocks/work/ubuntu-make/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/neon/R/eclipse-javascript-neon-R-linux-gtk-x86_64.tar.gz.sha512&r=1'
```
The file exists, but I guess the key isn't correctly adding to our dictionary, do you get the same?

**Comment by LyzardKing** [comment]
...My bad. It's trying to download the javascript version. Guess they changed the order. It works if I change the download-keyword from 'eclipse-java' to 'eclipse-java-'

**Comment by LyzardKing** [comment]
@didrocks I'll just check if the tests have different names, then I'll upload directly.

**Comment by vivekjib** [comment]
Still getting same error in this version while running through **_./umake_**.

**Comment by nenomina** [comment]
Hi guys, do you plan to update the ppa packages as well? All the eclipse links are broken unfortunately :(

**Comment by didrocks** [comment]
Yeah, sorry for the time before releasing due to summer holidays and other work priorities. A release will be done this week (I hope Thursday)

**Comment by kahukowhai** [comment]
Is this fix for a whole lot of URLs, I haven't tested all of them but Firefox Developer has the same error message. Tks

**Comment by LyzardKing** [comment]
Yes, this fixes the download link, so it's valid for default language settings and with the --lang option

**Comment by rugglcon** [comment]
The link for Firefox Developer still does not work, how is progress on this?

**Comment by LyzardKing** [comment]
@rugglcon Firefox-dev is working. What version of umake do you have? You might need to add the ppa

**Comment by rugglcon** [comment]
Ah I hadn't added the ppa. Which ppa is that? Is it one for umake or for firefox?

**Comment by kahukowhai** [comment]
Ubuntu Make has its own install page at wiki.ubuntu.com/ubuntu-make

The instructions on those are the ones that don't work because umake 
installs, but when you try to install Firefox Developer you get the 
error message.

If the Umake people can't do something as simple as correcting the 
instructions on this page (why it is not possible, apparently, to update 
the version of umake in the Universe archive so that we get one that 
works) then I do not know what I as a user of Xubuntu 16.04.1 LTS 
(Xenial) am supposed to do. The instructions clearly state that for 
16.04 I don't need any old PPA. Instead, I can install the package 
directly from the repository.

When I run sudo apt install ubuntu-make I get that I already have the 
latest version installed (16.02.1)

**Comment by LyzardKing** [comment]
You have to install the latest version, 16.11.1 if I recall correctly.
The ppa is needed to get the latest version.

**Comment by kahukowhai** [comment]
So how long does it take to edit a wiki page to say that?

It's been quite a few months that I haven't been able to use Firefox 
Developer on my computer because these instructions, on the official 
Ubuntu web site, are wrong.

**Comment by rugglcon** [comment]
That's a pretty valid point, why not just put the most recent version on the upstream repository?

**Comment by didrocks** [comment]
hey @kahukowhai! It's a wiki as you said, you can edit it yourself and contribute this way as you got that issue. We thank you in advance for doing it :)

@rugglcon: the issue is that new versions of Ubuntu Make includes new features and fixes. Introducing new features is forbidden as a stable release update. It means that someone has to backport fixed to the version corresponding to ubuntu 16.04 LTS, maintain that version, run tests, fix bugs. No-one stepped up for that.

Please note that nobody is paid for working on Ubuntu Make anymore, it's a pure community project where people helps on their free time. If you want to fix those issues, you are more than welcome to contribute.

**Comment by rugglcon** [comment]
Awesome, thank you for the information.

**Comment by rugglcon** [comment]
The ubuntu wiki page contains the correct information on installing, not
sure if it was updated in the last couple days but that information is
correct.

**Comment by Babu-Ameex** [comment]
Hi I am getting error while install "Firefox Developer Edition on Ubuntu 16.04"  in #step2
step 1: sudo apt install ubuntu-make
step 2: umake web firefox-dev
ERROR: Download page changed its syntax or is not parsable

**Comment by LyzardKing** [comment]
Did you add the PPA? You need an up to date versione of umake

**Comment by octopus-prime** [comment]
`umake ide eclipse-cpp`
->
ERROR: Download page changed its syntax or is not parsable

**Comment by kikolehm** [comment]
Same "ERROR: Download page changed its syntax or is not parsable" with umake version 18.05. Any help to workaround or fix this?

**Comment by narkan** [comment]
Same error: 
`$ umake android`
```
Choose installation path: /home/tc/.local/share/umake/android/android-studio
ERROR: Download page changed its syntax or is not parsable (url missing)
```

**Comment by myfbone** [comment]
> Same error:
> `$ umake android`
> 
> ```
> Choose installation path: /home/tc/.local/share/umake/android/android-studio
> ERROR: Download page changed its syntax or is not parsable (url missing)
> ```
> 
> Ubuntu 18.04

Did you solve the problem?

**Comment by LyzardKing** [comment]
what version of umake are you running?

**Comment by myfbone** [comment]
> what version of umake are you running?

I used ubuntu make from kubuntu repos. I don't know what version it was. 
But I solved the problem by adding ppa:ubuntu-desktop/ubuntu-make repository.
`sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make`

**Comment by LyzardKing** [comment]
You should use the ppa described in the README, it's updated more frequently

**Comment by ThanosFisherman** [comment]
Having this issue with umake 19.06 when I try to download android studio on  ZorinOS 15.2

**Comment by ThanosFisherman** [comment]
Any workarounds for this or should we wait for the next release?

**Comment by LyzardKing** [comment]
Please don't post on older issues.. it's hard to understand what the new issue is.
I'll look at the problem as soon as possible.
Thanks for reporting the issue
